### PR TITLE
Break out parser tests into separate files 

### PR DESCRIPTION
**Pull request by gitonthescene**
This makes it easier to reuse these examples for other tests like for the upcoming reorg-stringify or even simple debugging.  Adding new tests is simply a matter of creating a new file and referring to it in test.json.

### CODE REVIEW

**Comment by xiaoxinghu** [comment]
Hi, I haven't got the chance to write about testing yet. But I have refactored unit tests into subfolders, [tokenize/__tests__/](https://github.com/orgapp/orgajs/tree/master/packages/orga/src/tokenize/__tests__) and [parse/__tests__/](https://github.com/orgapp/orgajs/tree/master/packages/orga/src/parse/__tests__). I have ported most of the tokenize tests (use to be in `src/__tests__/lexer.ts`), but none of the parse tests yet (there's no assertion in the `parse/__tests__/` tests). one of the reasons for the moving is actually to break down tests into separate files. can you take a look at the `tokenize tests` and move the work into `parse/__tests__/`? Thanks.

**Comment by xiaoxinghu** [comment]
Oh, also, in order to include the tests in CI, test files need to be named `***.spec.ts`.

**Comment by gitonthescene** [comment]
Can you be more specific?  Which CI?  Can you link to the doc that specifies this requirement?  Without it I’d only be making wild guesses.

**Comment by gitonthescene** [comment]
Also, did you look at my diff?  It’s specifically about pulling the org source out of the tests.  It’s not clear what analogy you’re drawing to the tokenizer tests.

**Comment by gitonthescene** [comment]
Have you had a chance to view this pull request?

**Comment by xiaoxinghu** [comment]
this is not relevant since the big refactoring

**Pull request closed without merging**
